# Use root/example as user/password credentials
version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    ports:
      - "3360:3360"
    volumes:
      - "./data/mariadb_mondial.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MARIADB_ROOT_: mondial
      MARIADB_ROOT_PASSWORD: swordfish
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - "./data/neo4j_import:/import"
    environment:
      NEO4J_AUTH: neo4j/swordfish
  mongodb:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - "./mongo-seed/data:/docker-entrypoint-initdb.d/data"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mondial
      MONGO_INITDB_ROOT_PASSWORD: swordfish
  mongo-express:
    image: mongo-express
    container_name: mexpress
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mondial
      - ME_CONFIG_MONGODB_ADMINPASSWORD=swordfish
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=mondial
      - ME_CONFIG_BASICAUTH_PASSWORD=swordfish
  mongo-seed:
    build: ./mongo-seed
    depends_on: 
      - mongodb
