# Use root/example as user/password credentials
version: '3.8'

services:
  mariadb:
    image: mariadb:10.6.12
    restart: always
    container_name: mariadb
    ports:
      - "3360:3360"
      - "3306:3306"
    volumes:
      - "./data/mariadb_mondial.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MARIADB_ROOT_USERNAME: mondial
      MARIADB_ROOT_PASSWORD: swordfish
  mariadb_frontend:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
  neo4j:
    build: ./neo4j-seed
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/swordfish
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
  mongodb:
    image: mongo:6.0.3
    restart: always
    container_name: mongo
    environment:
      NEO4J_AUTH: neo4j/swordfish
      NEO4J_HOST: neo4j
    volumes:
      - "./mongo-seed/data:/docker-entrypoint-initdb.d/data"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mondial
      MONGO_INITDB_ROOT_PASSWORD: swordfish
  mongo-express:
    image: mongo-express
    container_name: mexpress
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mondial
      - ME_CONFIG_MONGODB_ADMINPASSWORD=swordfish
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=mondial
      - ME_CONFIG_BASICAUTH_PASSWORD=swordfish
  mongo-seed:
    build: ./mongo-seed
    depends_on: 
      - mongodb
