# Use root/example as user/password credentials
version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    ports:
      - "3360:3360"
    volumes:
      - "./data/mariadb_mondial.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MARIADB_ROOT_: mondial
      MARIADB_ROOT_PASSWORD: swordfish
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
    volumes:
      - "./data/neo4j_import:/import"
    environment:
      NEO4J_AUTH: neo4j/swordfish
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - "./mongo-seed/data:/docker-entrypoint-initdb.d/data"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mondial
      MONGO_INITDB_ROOT_PASSWORD: swordfish
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3300:3000
  mongo-seed:
    build: ./mongo-seed
    depends_on: 
      - mongodb
